all_users: [7, 9, 12, 15, 16, 20, 21, 23, 29, 35]
main_user: 12

cv_number: 6

K_means:
  param_grid:
    n_clusters: [1, 2, 3, 4, 5, 6, 7, 8]
    n_components: [4, 16, 15, 24, 32, null]
    whiten: [true]
    alpha: [0.2]

Isolation_forest:
  param_grid:
    n_components: [null]
    n_estimators: [32, 64, 100, 192]
    max_samples: [0.1, 0.4, 0.7, 1.0]
    max_features: [0.5, 0.75, 1.0]
    bootstrap: [true, false]
    alpha: [0.2]

XGBoost:
  param_grid:
    n_components: [null]
    max_depth: [3, 6, 9]
    learning_rate: [0.01, 0.1, 0.2]
    n_estimators: [50, 100, 200]
    max_leaves: [8, 16, 32, 64, 128]
    balancing: [proportional, SMOTE]

SVM:
  param_grid:
    n_components: [32, null]
    kernel: [poly, rbf]
    balancing: [proportional, SMOTE]

paths:
  raw_data_root: Mouse-Dynamics-Challenge-master
  preprocessed_data: data
  models: models
  results: results
  one_hot_encoding: models/ohe.pkl
  scaler: models/scaler.pkl

  K_means:
    all_results_name: kmeans_all_results.json
    best_results_name: kmeans_best_params.json
    model_name: kmeans_model.pkl
    preproc_name: kmeans_preproc.pkl

  Isolation_forest:
    all_results_name: if_all_results.json
    best_results_name: if_best_params.json
    model_name: if_model.pkl
    preproc_name: if_preproc.pkl

  XGBoost:
    all_results_name: xgb_all_results.json
    best_results_name: xgb_best_params.json
    model_name: xgb_model.pkl
    preproc: xgb_preproc.pkl
    
  SVM:
    all_results_name: svm_all_results.json
    best_results_name: svm_best_params.json
    model_name: svm_model.pkl
    preproc_name: svm_preproc.pkl
         
  