hydra:
    run:
        dir: outputs/${experiment_id}

timestamp: ${now:%d_%H-%M-%S}

experiment_id: hydra_tests_D${model.model.depth}_K${model.model.kernel_size}_H${model.model.hidden_channels}_SS${data.sequence_length}.${data.step}_${timestamp}

wandb:
    key: "WBKEY"
    project_name: "Rain_prediction"

data:
    _target_: src.data_modules.SEVIR_data_loader.ConvLSTMSevirDataModule
    files_dir: "PATH/TO/DATASET"
    sequence_length: 8
    step: 6
    width: 64
    height: 64
    batch_size: 1024
    num_workers: 2
    train_files_percent: 0.7
    val_files_percent: 0.15
    test_files_percent: 0.15

early_stopping:
    _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: "validation_loss"
    patience: 8
    verbose: False
    mode: "min"

checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "validation_loss"
    dirpath: "./model/"
    filename: "model-{epoch:02d}-{validation_loss:.2f}"
    save_top_k: 3
    mode: "min"

model:
    _target_: src.predictors.rain_predictor.RainPredictor
    mapping_kernel_size: 3
    learning_rate: 0.01
    scheduler_step: 10
    scheduler_gamma: 0.1
    model:
        _target_: src.architectures.conv_rnn.ConvRNNCell
        input_channels: 1
        hidden_channels: 8
        kernel_size: 5
        depth: 1
        activation:
            _target_: torch.nn.ReLU

    mapping_activation:
        _target_: torch.nn.ReLU

    loss_metrics:
        _target_: torchmetrics.MeanSquaredError
        squared: true

trainer:
    accelerator: "gpu"
    devices: [0]
    max_epochs: 50
    num_visualised_samples: 6
